language: node_js
os: linux
dist: bionic
node_js:
  12
before_script:
  - npm install -g gulp@4.0.2
env:
  global:
    secure: XRBd6nQh+myZQT6del6/Kvm+FSgk+2mK4WpbkHPAtLZPpY/Ltnp4DQo1MCNQ4IM+06u/rwrgS5qZd1V2xYRGFcOU02efkWAjhl5LoJhzTsIV/6CkpPW6FNJ5S1EjOLzgzy61xkbPkV4mSBSSZ/740EP08QJszv55Akkj4bo/X219F43WtO0upGM1SNKbeiYBDAXOh+Dh3GZOIX0bKFjhytrR9lkrdrUVY+Rx8W2yz59ovW074vN8QqUn2J6ZXPyB1TszG8Dr4qwHcS1Tg898DTHM5EU1/yadWW8WlDkf34bFdbtp+Hhe1iZ0BYkcrQAXefn+6dICMc/blsasohMQeViprf/ILpB2XBX3WdwyYWq/CZAkhqEPtFgvdstYZEUxetWucCTEX6bziTDGl7oYQ7iApR09vek5zgaUOfJb9psyC7cGfqjuap2znomSzcb3qo9EzOX36HRQaes1uLIe41TuRYVR++ByUjoOKr8N1AGR0maGZ2F3SYlzLfIwgq3TAn37vAcF8UwsXb0ULHyA1qDy0dkEXnTUICnKskCrB6NJZKqAf5rVkJ0vfRsAMQep1JQNv5Two5UAD2uh/V2udOiMK6DwVAx56w2WmEN70DhVtOKnya21lywWjIThPe+0QsSMLcXan+BUhvxNL6qzBQlMsxgtuTni+NqXAfsAPPM=
script: gulp build
deploy:
  provider: pages
  cleanup: false
  keep_history: true
  strategy: git
  local_dir: dist
  on:
    branch: master
  edge: true