language: node_js
os: linux
dist: bionic
node_js:
  12
before_script:
  - npm install -g gulp@4.0.2
env:
  global:
    secure: A3y8iBbvTEZTfnxhlqmH8nYJHaXeTglrsDJZmHICiD+yswH4MBQhWWio1bV/xRWF0zOczYPStFCCoHynVxVkuPlkjui+M1j1bSdDjslsyABACv4bb+g7Wt+PzL1kyI3BLJA7pRAXksArty6Pz7jmzEuw3c5Y+bD11TJXTieSRAsFKirbUG+URZa51JIfbaDx+OMQ/C09XyIOAWKO4p3fhlIF2EUn0pxt9MUzGKEdDC0wawHsBTwjyoFJ1+HgnjsaQD5VdKuG/xZ6j0wCOLGQ6ELLNGfAADrFQrneUmvOQLIKVR6fWVOKG+6muITQ+uEr7ws9QM8KUzZFV5eIP40JB/vm48k0ORp3OjUq2XpvXCtRuw44R3Tmj1TYgQIKPUYdOXtXBI55rZlNPyZPXaFNHK/hxTln5hUCuM1eFwXMY5S/sNHW+kXK9J23JV5io2XlfpuZJnfgGIH7etFR67anjUET+ee2XvtsTbML3K8jx8trkDryhsGa+H6nMLlSCdX3WCqgFJMgqQoEzuoRAXppmS64VAW2Rl1pgf/ILKvpH2dnlSgr8egnGmcNHOLuCvw2DHSMxOB1UaiGL1bzl3NIUkzOyYlCEv3e/YyzV0MLYqUdxJbUk91LXFQ7coOd/DYlQddzAU1APMHRcSPs4aMN2WSjxw5iMCDCerL6uGPKyAo=
script: gulp build
deploy:
  provider: pages
  cleanup: false
  keep_history: true
  strategy: git
  local_dir: dist
  on:
    branch: master
  edge: true
