language: node_js
os: linux
dist: bionic
node_js:
  12
before_script:
  - npm install -g gulp@4.0.2
env:
  global:
    secure: ZnwwSsCFHim0qIJmiwwcG5RiPEWNK3Uvpvk/kuUop7/CDXg71UgM9c5od/kTHzQ5I3szbERB4ngZoXMyPgjtKGqkC3CdO/oG5qehoyIq/AJL6S1hR4lu2/APh6G4goyYko7lrdcpuSz+hOLC6IiFRJirO+fK4ndXUjuamIHK7GKQm9nXGj+lrwSoSoIeKalO91xOXyCRHKgqpIS3NWW8L3g5pedQAjHqKFxxzxQym8BQlIHGNuNtIdOmWp4Kx+6tchkW1yw0Z5jhDJyFzIL4HBa+ftaE0Ve52LMRys+80/dfK1mgfJEGnz8ALnLRv8qApBCuORhzkKDMw8ffqLqOJIjDqeMLNEv2JpI30RIFVMOWL6r3epRBnp4fFNe7981BwsKCu9YZ46BslNfPQTfGYpq6By3PYvFRa1G2ugHry+nnA3urKoGtn0b/RSegAq5Am+kOvhcONPGCrUdUWhD343C8uuzqQyDYi9UDaoZ1214Pwh6I/qQh2RZ6kxBp8vJBqNVjMh/Yop4GCsaNKVGohQGpzFg0vZoVaLMJi6gXQzJqmISVxVozgZ0QdIaZt1VHOn1SGfjNc3ST8KDs2UQ02qwJFwzUJgziPHB4lwXtnx9QsDoDLbLeXcu7HPziGVW5tS8S2qO5sJ28yDI7/R/CiyshnM2AC5wn2ug+VAuJK+k=
script: gulp build
deploy:
  provider: pages
  cleanup: false
  keep_history: true
  strategy: git
  local_dir: dist
  on:
    branch: master
  edge: true